#!/bin/bash
#SBATCH --job-name=forklift-dpo
#SBATCH -p gpuL
#SBATCH -G 1
#SBATCH --cpus-per-task=12
#SBATCH --mem=125G
#SBATCH -t 2-0
#SBATCH --output=logs/dpo_train_%j.out
#SBATCH --error=logs/dpo_train_%j.err

# ──────────────────────────────────────────────────────────────
# SLURM launcher: DPO fine-tuning with compiler feedback.
#
# Stage 2 of the DPO pipeline:
#   1. generate_dpo_pairs.py  →  preference dataset  (run first)
#   2. dpo_finetune.py        →  DPO-trained model    (this script)
#
# The DPO loss teaches the model to prefer outputs that compile
# over outputs that don't, using the compiler as an automatic
# preference oracle.
#
# Usage:
#   sbatch scripts/train_dpo_csf.sh
#   sbatch scripts/train_dpo_csf.sh --max_steps 10000
# ──────────────────────────────────────────────────────────────

set -euo pipefail

echo "Starting DPO training at $(date)"
echo "Job ID: ${SLURM_JOB_ID:-local}"
echo "Host: $(hostname)"

# ── Environment ──────────────────────────────────────────────
cd "${SLURM_SUBMIT_DIR:-$(dirname "$0")/..}"
mkdir -p logs

# Activate virtual environment if present
if [ -f "env/bin/activate" ]; then
    source env/bin/activate
fi

export PATH="$HOME/scratch/forklift/tools/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04/bin:$PATH"

export EXEBENCH_CLIB_DIR="$HOME/scratch/exebench/exebench"

# ── Model to start from ─────────────────────────────────────
# Start from the v2 arm-ir-ir checkpoint (same as SFT model).
MODEL_PATH="${MODEL_PATH:-checkpoints/arm_ir_ir_v4/step_80000}"

# ── DPO dataset ──────────────────────────────────────────────
# Generated by scripts/generate_dpo_csf.sh (or generate_dpo_pairs.py)
DPO_DATASET="${DPO_DATASET:-dpo_pairs/}"

# ── Launch DPO training ──────────────────────────────────────
python -m neurel_deob.training.dpo_finetune \
    --model_path "$MODEL_PATH" \
    --dpo_dataset "$DPO_DATASET" \
    --max_steps 200 \
    --batch_size 2 \
    --gradient_accumulation_steps 8 \
    --lr 1e-7 \
    --lr_scheduler cosine \
    --warmup_steps 20 \
    --beta 0.2 \
    --fp16 \
    --eval_steps 50 \
    --save_steps 50 \
    --eval_samples 200 \
    --checkpoint_dir "checkpoints/dpo" \
    --tensorboard_dir "runs/dpo" \
    "$@"

echo "DPO training finished at $(date)"
